fn = '/path/to/file.tsv';
ex = mcread(fn);

% replace NaNs generated by mcread back to zeros
ex.data(isnan(ex.data)) = 0;


%% Animation parameters: name of video file, filetype, bones and marker/bone visuals
anipar = mcinitanimpar;
anipar.animate = 1;
anipar.output = fn(1:end-4);
anipar.videoformat = 'mp4';
anipar.colors = 'wbkkk';
anipar.msize=6;
anipar.showmnum = 1;
anipar.showfnum = 1;
anipar.conn = [ 2 13; 2 18; 12 19; 12 14; 1 2; 2 7; 2 3; 3 4; 4 5; 5 6; 7 8; 8 9; 9 10; 2 11; 11 12; 18 11; 11 13; 18 12; 13 12; 13 14; 14 15; 15 17; 17 16;18 19; 19 20; 20 21; 21 22;];%15 16; 16 17; 18 19; 19 20; 20 21; 21 22;];
%%
mcanimate(ex,anipar)